export declare const DEFAULT_SRC = "default";
export declare const DEFAULT_MODIFY_CHECKBOX: string;
export declare const DEFAULT_MODIFY_URL: string;
export declare const DEFAULT_ADD_EMPTY_URL: string;
export declare const DEFAULT_ADD_URL: string;
export declare const DEFAULT_DELETE_URL: string;
export declare const IMG_SRC = "img";
export declare const IMG_MODIFY_CHECKBOX: string;
export declare const IMG_MODIFY_URL: string;
export declare const IMG_ADD_EMPTY_URL: string;
export declare const IMG_ADD_URL: string;
export declare const IMG_DELETE_URL: string;
export declare const STYLE_SRC = "style";
export declare const STYLE_MODIFY_CHECKBOX: string;
export declare const STYLE_MODIFY_URL: string;
export declare const STYLE_ADD_EMPTY_URL: string;
export declare const STYLE_ADD_URL: string;
export declare const STYLE_DELETE_URL: string;
export declare const SCRIPT_SRC = "script";
export declare const SCRIPT_MODIFY_CHECKBOX: string;
export declare const SCRIPT_MODIFY_URL: string;
export declare const SCRIPT_ADD_EMPTY_URL: string;
export declare const SCRIPT_ADD_URL: string;
export declare const SCRIPT_DELETE_URL: string;
export declare const FRAME_SRC = "frame";
export declare const FRAME_MODIFY_CHECKBOX: string;
export declare const FRAME_MODIFY_URL: string;
export declare const FRAME_ADD_EMPTY_URL: string;
export declare const FRAME_ADD_URL: string;
export declare const FRAME_DELETE_URL: string;
export declare const FONT_SRC = "font";
export declare const FONT_MODIFY_CHECKBOX: string;
export declare const FONT_MODIFY_URL: string;
export declare const FONT_ADD_EMPTY_URL: string;
export declare const FONT_ADD_URL: string;
export declare const FONT_DELETE_URL: string;
export declare const OBJECT_SRC = "object";
export declare const OBJECT_MODIFY_CHECKBOX: string;
export declare const OBJECT_MODIFY_URL: string;
export declare const OBJECT_ADD_EMPTY_URL: string;
export declare const OBJECT_ADD_URL: string;
export declare const OBJECT_DELETE_URL: string;
export declare const RESET_DATA = "reset_data";
